require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AngloAcademy' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNAudioJack', :path => '../node_modules/react-native-audio-jack'

  target 'AngloAcademyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AngloAcademy-tvOS' do
  # Pods for AngloAcademy-tvOS

  target 'AngloAcademy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
